### ISSUE TITLE
Trying to edit blockmodel with blockbench.exe.

### ISSUE THREAD

**Issue by VergilPrime** [mcRPW/rpw#139]
**What happened?**

Crash message!

**Steps to reproduce:**

Click "Edit Model" with Blockbench set as your block model editor.

**Crash report (if any)**
## RPW 4.5.2 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.

Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com

### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.8.0_144
 Java vendor       | Oracle Corporation
 Java path         | C:\Program Files\Java\jre1.8.0_144
 OS name           | Windows 10
 OS arch           | amd64
 File encoding     | Cp1252
 Launch dir        | C:\Users\Vergi\Desktop
 RPW version       | 4.5.2
 Library version   | 1.12.2
 RPW path          | C:\Users\Vergi\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\Vergi\AppData\Roaming\.minecraft

### STACK TRACE ###

```
java.lang.NullPointerException
	at net.mightypork.rpw.tasks.TaskModifyAsset.editModel(TaskModifyAsset.java:103)
	at net.mightypork.rpw.tasks.Tasks.taskEditModel(Tasks.java:813)
	at net.mightypork.rpw.gui.widgets.SidePanel$9.actionPerformed(SidePanel.java:719)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

### FULL LOG ###

```
[ i ] Main logger initialized.
[ i ] 2017/12/14 01:23:33
[ i ] ResourcePack Workbench v.4.5.2 (#452)
[ # ] Init started...
[ - ] Project 'AngelFaith': Creating backup copy...
[ - ] Project 'AngelFaith': Copying - done.
[ - ] Project 'AngelFaith': Loading from workdir
[   ] Adding RPW_README.txt to the pack
[ - ] Checking Minecraft installation.
[ - ] Initializing configuration manager.
[ - ] Checking working directory.
[   ] Last run version: 4.5.2 (#452)
[ i ] Using library version: 1.12.2
[ - ] Loading GUI icons
[ - ] Loading GUI icons - done.
[   ] Initializing RSyntaxTextArea
[ - ] Loading help pages
[ # ] Initializing Sources
[ - ] Loading vanilla structure
[ - ] Loading help pages - done.
[ - ] Loading vanilla structure - done.
[ - ] Erasing library cache
[ - ] Loading resourcepacks...
[ # ] Initializing Sources - done.
[ - ] Building main window.
[ - ] Downloading update info
[ - ] Opening last project (if any).
[ # ] Loading project AngelFaith
[ - ] Project 'AngelFaith': Creating backup copy...
[ - ] Project 'AngelFaith': Copying - done.
[ - ] Project 'AngelFaith': Loading from workdir
[   ] Adding RPW_README.txt to the pack
[ - ] Downloading update info - done.
[ i ] Your version is up-to-date.
[   ] Dialog open: Manage Projects
[   ] Dialog closed: Manage Projects
[   ] Dialog open: New Project
[   ] Dialog closed: New Project
[ - ] Project 'AngelFaith': Creating backup copy...
[ - ] Project 'AngelFaith': Copying - done.
[ - ] Project 'AngelFaith': Loading from workdir
[   ] Adding default pack icon
[   ] Adding RPW_README.txt to the pack
[   ] Dialog open: Loading Resource Pack
[ # ] Loading resource pack to project
[   ] Pack file: C:\Users\Vergi\Desktop\AngelFaith.zip
[ - ] Listing pack file
[ - ] Loading custom languages
[   ] + pack.png
[!E!] java.lang.StringIndexOutOfBoundsException: String index out of range: -56
[!E!] 	at java.lang.String.substring(Unknown Source)
[!E!] 	at net.mightypork.rpw.struct.PackMcmeta.fromJson(PackMcmeta.java:38)
[!E!] 	at net.mightypork.rpw.tasks.sequences.SequencePopulateProjectFromPack.stepMcmetaAndLanguages(SequencePopulateProjectFromPack.java:143)
[!E!] 	at net.mightypork.rpw.tasks.sequences.SequencePopulateProjectFromPack.step(SequencePopulateProjectFromPack.java:91)
[!E!] 	at net.mightypork.rpw.tasks.sequences.AbstractSequence.run(AbstractSequence.java:100)
[!E!] 	at net.mightypork.rpw.tasks.sequences.AbstractSequence.run(AbstractSequence.java:71)
[!E!] 	at net.mightypork.rpw.tasks.Tasks$18.run(Tasks.java:923)
[!E!] 	at java.lang.Thread.run(Unknown Source)
[!E!] 
[ # ] Loading resource pack to project - done.
[ i ] Import successful.
[!W!] Sequence failed at step #1: Loading custom languages
[   ] Dialog closed: Loading Resource Pack
[   ] Dialog open: Manage Projects
[   ] Dialog closed: Manage Projects
[   ] Dialog open: New Project
[   ] Dialog closed: New Project
[ - ] Project 'AngelFaith': Creating backup copy...
[ - ] Project 'AngelFaith': Copying - done.
[ - ] Project 'AngelFaith': Loading from workdir
[   ] Adding default pack icon
[   ] Adding RPW_README.txt to the pack
[   ] Dialog open: Quick Guide
[   ] Dialog closed: Quick Guide
[   ] Dialog open: Select target Minecraft version
[ - ] Looking for installed Minecraft versions.
[   ] Version 1.12.2
[   ] - valid
[   ] Version 1.12.2-OptiFine_HD_U_C6
[   ] - valid
[   ] Dialog closed: Select target Minecraft version
[   ] Dialog open: Quick Guide
[   ] Dialog closed: Quick Guide
[   ] Dialog open: Project Properties
[   ] Dialog closed: Project Properties
[ - ] Trying to exec:
[ - ]    cmd = C:\Program Files (x86)\Adobe\Photoshop Elements 11\PhotoshopElementsEditor.exe
[ - ]    args = %s
[ - ]    %s = C:\Users\Vergi\AppData\Roaming\.mcRPW\projects\AngelFaith\project_files\assets\minecraft\textures\blocks\mob_spawner.png
[   ] Process is running.
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.NullPointerException
[!E!] 	at net.mightypork.rpw.tasks.TaskModifyAsset.editModel(TaskModifyAsset.java:103)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskEditModel(Tasks.java:813)
[!E!] 	at net.mightypork.rpw.gui.widgets.SidePanel$9.actionPerformed(SidePanel.java:719)
[!E!] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[!E!] 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
[!E!] 	at java.awt.Component.processMouseEvent(Unknown Source)
[!E!] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.Component.processEvent(Unknown Source)
[!E!] 	at java.awt.Container.processEvent(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.EventQueue.access$500(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.run(Unknown Source)
[!E!] 
[   ] Dialog open: RPW has crashed!
[ - ] Trying to exec:
[ - ]    cmd = explorer
[ - ]    args = %s
[ - ]    %s = https://github.com/mcRPW/rpw/issues/new
[   ] Process is running.
[   ] Dialog closed: RPW has crashed!
[   ] Dialog open: Configure Editors
[   ] Dialog closed: Configure Editors
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.NullPointerException
[!E!] 	at net.mightypork.rpw.tasks.TaskModifyAsset.editModel(TaskModifyAsset.java:103)
[!E!] 	at net.mightypork.rpw.tasks.Tasks.taskEditModel(Tasks.java:813)
[!E!] 	at net.mightypork.rpw.gui.widgets.SidePanel$9.actionPerformed(SidePanel.java:719)
[!E!] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[!E!] 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
[!E!] 	at java.awt.Component.processMouseEvent(Unknown Source)
[!E!] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.Component.processEvent(Unknown Source)
[!E!] 	at java.awt.Container.processEvent(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.EventQueue.access$500(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$3.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.awt.EventQueue$4.run(Unknown Source)
[!E!] 	at java.security.AccessController.doPrivileged(Native Method)
[!E!] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[!E!] 	at java.awt.EventDispatchThread.run(Unknown Source)
[!E!] 

```

~~~ END OF REPORT ~~~

**Comment by MCrafterzz** [comment]
Try latest version
