### ISSUE TITLE
I might be an idiot?

### ISSUE THREAD

**Issue by SparklySpencer** [mcRPW/rpw#143]
*******************************************

IF YOU ARE REPORTING A BROKEN DOWNLOAD LINK:

There is nothing we can do with Dropbox breaking the links.

Go download it from the releases page here on GitHub, or https://mcrpw.github.io/

*******************************************
<- Delete this notice before sending!

**What happened?**

... I'm apparently a noob and don't know what I am doing ...

**Steps to reproduce:**

... added new textures, saved, and tried to export...

**Crash report (if any)**

...## RPW 4.5.2 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.

Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com

### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.8.0_151
 Java vendor       | Oracle Corporation
 Java path         | C:\Program Files (x86)\Java\jre1.8.0_151
 OS name           | Windows 10
 OS arch           | x86
 File encoding     | Cp1252
 Launch dir        | C:\Users\spenc\Downloads
 RPW version       | 4.5.2
 Library version   | 1.12.2
 RPW path          | C:\Users\spenc\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\spenc\AppData\Roaming\.minecraft

### STACK TRACE ###

```
java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferByte.<init>(Unknown Source)
	at java.awt.image.ComponentSampleModel.createDataBuffer(Unknown Source)
	at java.awt.image.Raster.createWritableRaster(Unknown Source)
	at javax.imageio.ImageTypeSpecifier.createBufferedImage(Unknown Source)
	at javax.imageio.ImageReader.getDestination(Unknown Source)
	at com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
	at com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
	at javax.imageio.ImageIO.read(Unknown Source)
	at javax.imageio.ImageIO.read(Unknown Source)
	at com.pixbits.rpw.stitcher.AssetImage.cacheImage(AssetImage.java:91)
	at com.pixbits.rpw.stitcher.Tasks.exportPackToStitchedPng(Tasks.java:114)
	at com.pixbits.rpw.stitcher.DialogExportStitch$2.actionPerformed(DialogExportStitch.java:299)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)

```

### FULL LOG ###

```
[ i ] Main logger initialized.
[ i ] 2018/02/22 23:40:55
[ i ] ResourcePack Workbench v.4.5.2 (#452)
[ # ] Init started...
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Loading from workdir
[   ] Adding RPW_README.txt to the pack
[ - ] Checking Minecraft installation.
[ - ] Initializing configuration manager.
[ - ] Checking working directory.
[   ] Last run version: 4.5.2 (#452)
[ i ] Using library version: 1.12.2
[ - ] Loading GUI icons
[ - ] Loading GUI icons - done.
[   ] Initializing RSyntaxTextArea
[ - ] Loading help pages
[ # ] Initializing Sources
[ - ] Loading vanilla structure
[ - ] Loading help pages - done.
[ - ] Loading vanilla structure - done.
[ - ] Erasing library cache
[ - ] Loading resourcepacks...
[ # ] Initializing Sources - done.
[ - ] Building main window.
[ - ] Downloading update info
[ - ] Opening last project (if any).
[ # ] Loading project Sparkles
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Loading from workdir
[   ] Adding RPW_README.txt to the pack
[ - ] Downloading update info - done.
[ i ] Your version is up-to-date.
[   ] Dialog open: New Project
[   ] Dialog closed: New Project
[ - ] Trying to exec:
[ - ]    cmd = explorer
[ - ]    args = %s
[ - ]    %s = C:\Users\spenc\AppData\Roaming\.mcRPW\projects\Sparkles
[   ] Process is running.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[ - ] Project 'Sparkles': Creating backup copy...
[ - ] Project 'Sparkles': Copying - done.
[   ] Dialog open: Export Stitch
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.OutOfMemoryError: Java heap space
[!E!] 	at java.awt.image.DataBufferByte.<init>(Unknown Source)
[!E!] 	at java.awt.image.ComponentSampleModel.createDataBuffer(Unknown Source)
[!E!] 	at java.awt.image.Raster.createWritableRaster(Unknown Source)
[!E!] 	at javax.imageio.ImageTypeSpecifier.createBufferedImage(Unknown Source)
[!E!] 	at javax.imageio.ImageReader.getDestination(Unknown Source)
[!E!] 	at com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
[!E!] 	at com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
[!E!] 	at javax.imageio.ImageIO.read(Unknown Source)
[!E!] 	at javax.imageio.ImageIO.read(Unknown Source)
[!E!] 	at com.pixbits.rpw.stitcher.AssetImage.cacheImage(AssetImage.java:91)
[!E!] 	at com.pixbits.rpw.stitcher.Tasks.exportPackToStitchedPng(Tasks.java:114)
[!E!] 	at com.pixbits.rpw.stitcher.DialogExportStitch$2.actionPerformed(DialogExportStitch.java:299)
[!E!] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[!E!] 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
[!E!] 	at java.awt.Component.processMouseEvent(Unknown Source)
[!E!] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.Component.processEvent(Unknown Source)
[!E!] 	at java.awt.Container.processEvent(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.EventQueue.access$500(Unknown Source)
[!E!] 
[   ] Dialog open: RPW has crashed!
[   ] Dialog closed: RPW has crashed!
[!E!] Unhandled error, opening error screen.
[!E!] java.lang.OutOfMemoryError: Java heap space
[!E!] 	at java.awt.image.DataBufferByte.<init>(Unknown Source)
[!E!] 	at java.awt.image.ComponentSampleModel.createDataBuffer(Unknown Source)
[!E!] 	at java.awt.image.Raster.createWritableRaster(Unknown Source)
[!E!] 	at javax.imageio.ImageTypeSpecifier.createBufferedImage(Unknown Source)
[!E!] 	at javax.imageio.ImageReader.getDestination(Unknown Source)
[!E!] 	at com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
[!E!] 	at com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
[!E!] 	at javax.imageio.ImageIO.read(Unknown Source)
[!E!] 	at javax.imageio.ImageIO.read(Unknown Source)
[!E!] 	at com.pixbits.rpw.stitcher.AssetImage.cacheImage(AssetImage.java:91)
[!E!] 	at com.pixbits.rpw.stitcher.Tasks.exportPackToStitchedPng(Tasks.java:114)
[!E!] 	at com.pixbits.rpw.stitcher.DialogExportStitch$2.actionPerformed(DialogExportStitch.java:299)
[!E!] 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[!E!] 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[!E!] 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
[!E!] 	at java.awt.Component.processMouseEvent(Unknown Source)
[!E!] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.Component.processEvent(Unknown Source)
[!E!] 	at java.awt.Container.processEvent(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[!E!] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.Component.dispatchEvent(Unknown Source)
[!E!] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[!E!] 	at java.awt.EventQueue.access$500(Unknown Source)
[!E!] 

```

~~~ END OF REPORT ~~~

**Comment by MCrafterzz** [comment]
It's a java heap space error which randomly occurs will all programs even Minecraft itself so unfortunly there's nothing that we can do. Try updating your java version that sometimes solves it
