### ISSUE TITLE
When I try to change models it appear, but I already have BlockBench ;-;

### ISSUE THREAD

**Issue by Inhister** [mcRPW/rpw#159]
## RPW 4.5.2 CRASH REPORT ##

Please, report this issue on GitHub (use the button below).
If possible, include THIS WHOLE LOG in the report.

Alternatively, you can send this log to MightyPork.
	E-mail: ondra@ondrovo.com

### SYSTEM INFO ###

 Key               | Value 
-------------------|-------------------------------
 Runtime name      | Java(TM) SE Runtime Environment
 Java version      | 1.8.0_181
 Java vendor       | Oracle Corporation
 Java path         | C:\Program Files\Java\jre1.8.0_181
 OS name           | Windows 10
 OS arch           | amd64
 File encoding     | Cp1252
 Launch dir        | C:\Users\Vinicius\Desktop
 RPW version       | 4.5.2
 Library version   | 1.13
 RPW path          | C:\Users\Vinicius\AppData\Roaming\.mcRPW
 Minecraft path    | C:\Users\Vinicius\AppData\Roaming\.minecraft

### STACK TRACE ###

```
java.lang.NullPointerException
	at net.mightypork.rpw.tasks.TaskModifyAsset.editModel(TaskModifyAsset.java:103)
	at net.mightypork.rpw.tasks.Tasks.taskEditModel(Tasks.java:813)
	at net.mightypork.rpw.gui.widgets.SidePanel$9.actionPerformed(SidePanel.java:719)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

~~~ END OF REPORT ~~~

**Comment by MCrafterzz** [comment]
https://github.com/mcRPW/rpw/issues/155
